version: '3.8'

services:
  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_ERLANG_COOKIE=my_secret_cookie_123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 20s

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logs_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  seq:
    image: datalust/seq:latest
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=password123
    ports:
      - "5341:5341"
      - "8081:80"
    volumes:
      - seq_data:/data
    restart: always
  
  logger:
    build:
      context: .
      dockerfile: LoggerService/Dockerfile
    environment:
      - LoggerSettings__RabbitMqHost=rabbitmq
      - LoggerSettings__UserName=admin
      - LoggerSettings__Password=admin
      - LoggerSettings__ConnectionString=Host=postgres;Port=5432;Database=logs_db;Username=postgres;Password=admin
      - SEQ_API_KEY=frfbl5kkuNF4veiO0Scq
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started

  producer:
    build:
      context: .
      dockerfile: Producer/Dockerfile
    environment:
      - ProducerSettings__RabbitMqHost=rabbitmq
      - ProducerSettings__UserName=admin
      - ProducerSettings__Password=admin
      - ProducerSettings__QueueName=work_queue
      - SEQ_API_KEY=frfbl5kkuNF4veiO0Scq
    depends_on:
      rabbitmq:
        condition: service_healthy

  consumer:
    build:
      context: .
      dockerfile: Consumer/Dockerfile
    environment:
      - ConsumerSettings__RabbitMqHost=rabbitmq
      - ConsumerSettings__UserName=admin
      - ConsumerSettings__Password=admin
      - ConsumerSettings__QueueName=work_queue
      - SEQ_API_KEY=frfbl5kkuNF4veiO0Scq
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  seq_data:
  postgres_data: 